export type USACity = {
    slug: string;
    name: string;
    state: string;
    stateCode: string;
    population: string;
    knownFor: string;
    businessScene: string;
    techHub: boolean;
    region: 'Northeast' | 'South' | 'Midwest' | 'West';
    localKeyword: string;
    uniqueFact: string;
    nearbyCity: string;
    nearbyCitySlug: string;
    timezone: string;
    industries: string[];
};

export const usaCities: USACity[] = [
    {
        slug: "new-york-city",
        name: "New York City",
        state: "New York",
        stateCode: "NY",
        population: "8.3 million",
        knownFor: "finance, media, and tech startups",
        businessScene: "competitive enterprise market",
        techHub: true,
        region: "Northeast",
        localKeyword: "NYC web design",
        uniqueFact: "New York City has more than 200,000 businesses.",
        nearbyCity: "Jersey City",
        nearbyCitySlug: "jersey-city",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Media", "Fashion", "Healthcare"]
    },
    {
        slug: "los-angeles",
        name: "Los Angeles",
        state: "California",
        stateCode: "CA",
        population: "3.8 million",
        knownFor: "entertainment, aerospace, and fashion",
        businessScene: "vibrant creative economy",
        techHub: true,
        region: "West",
        localKeyword: "LA web development",
        uniqueFact: "LA is the entertainment capital of the world.",
        nearbyCity: "Long Beach",
        nearbyCitySlug: "long-beach",
        timezone: "Pacific Time (PT)",
        industries: ["Entertainment", "Aerospace", "Tourism", "Technology"]
    },
    {
        slug: "chicago",
        name: "Chicago",
        state: "Illinois",
        stateCode: "IL",
        population: "2.6 million",
        knownFor: "manufacturing, finance, and food processing",
        businessScene: "diverse industrial base",
        techHub: true,
        region: "Midwest",
        localKeyword: "Chicago website development",
        uniqueFact: "Chicago is home to the first skyscraper in the world.",
        nearbyCity: "Milwaukee",
        nearbyCitySlug: "milwaukee",
        timezone: "Central Time (CT)",
        industries: ["Manufacturing", "Finance", "Healthcare", "Transportation"]
    },
    {
        slug: "houston",
        name: "Houston",
        state: "Texas",
        stateCode: "TX",
        population: "2.3 million",
        knownFor: "energy, aeronautics, and healthcare",
        businessScene: "global energy hub",
        techHub: true,
        region: "South",
        localKeyword: "Houston web development",
        uniqueFact: "Houston is the most diverse city in the United States.",
        nearbyCity: "San Antonio",
        nearbyCitySlug: "san-antonio",
        timezone: "Central Time (CT)",
        industries: ["Energy", "Healthcare", "Aerospace", "Manufacturing"]
    },
    {
        slug: "phoenix",
        name: "Phoenix",
        state: "Arizona",
        stateCode: "AZ",
        population: "1.6 million",
        knownFor: "electronics, tourism, and agriculture",
        businessScene: "rapidly growing tech corridor",
        techHub: true,
        region: "West",
        localKeyword: "Phoenix software development",
        uniqueFact: "Phoenix is the only state capital with over one million people.",
        nearbyCity: "Mesa",
        nearbyCitySlug: "mesa",
        timezone: "Mountain Time (MT)",
        industries: ["Electronics", "Tourism", "Finance", "Healthcare"]
    },
    {
        slug: "philadelphia",
        name: "Philadelphia",
        state: "Pennsylvania",
        stateCode: "PA",
        population: "1.5 million",
        knownFor: "education, healthcare, and biotech",
        businessScene: "historic and evolving economy",
        techHub: true,
        region: "Northeast",
        localKeyword: "Philadelphia web design",
        uniqueFact: "Philadelphia was the first capital of the United States.",
        nearbyCity: "Newark",
        nearbyCitySlug: "newark",
        timezone: "Eastern Time (ET)",
        industries: ["Education", "Healthcare", "Manufacturing", "Finance"]
    },
    {
        slug: "san-antonio",
        name: "San Antonio",
        state: "Texas",
        stateCode: "TX",
        population: "1.4 million",
        knownFor: "military, healthcare, and tourism",
        businessScene: "steady and diverse local economy",
        techHub: false,
        region: "South",
        localKeyword: "San Antonio web development",
        uniqueFact: "The Alamo is located in the heart of San Antonio.",
        nearbyCity: "Austin",
        nearbyCitySlug: "austin",
        timezone: "Central Time (CT)",
        industries: ["Military", "Healthcare", "Tourism", "Finance"]
    },
    {
        slug: "san-diego",
        name: "San Diego",
        state: "California",
        stateCode: "CA",
        population: "1.3 million",
        knownFor: "defense, biotech, and tourism",
        businessScene: "innovation-driven coastal market",
        techHub: true,
        region: "West",
        localKeyword: "San Diego web services",
        uniqueFact: "San Diego is known as 'America's Finest City'.",
        nearbyCity: "Los Angeles",
        nearbyCitySlug: "los-angeles",
        timezone: "Pacific Time (PT)",
        industries: ["Defense", "Biotechnology", "Tourism", "Technology"]
    },
    {
        slug: "dallas",
        name: "Dallas",
        state: "Texas",
        stateCode: "TX",
        population: "1.2 million",
        knownFor: "telecommunications, electronics, and finance",
        businessScene: "major corporate headquarters hub",
        techHub: true,
        region: "South",
        localKeyword: "Dallas IT solutions",
        uniqueFact: "Dallas is home to the largest arts district in the US.",
        nearbyCity: "Fort Worth",
        nearbyCitySlug: "fort-worth",
        timezone: "Central Time (CT)",
        industries: ["Telecommunications", "Finance", "Transportation", "Media"]
    },
    {
        slug: "san-jose",
        name: "San Jose",
        state: "California",
        stateCode: "CA",
        population: "970,000",
        knownFor: "high-tech and innovation",
        businessScene: "capital of Silicon Valley",
        techHub: true,
        region: "West",
        localKeyword: "San Jose web dev",
        uniqueFact: "San Jose has more patents per capita than any other city.",
        nearbyCity: "San Francisco",
        nearbyCitySlug: "san-francisco",
        timezone: "Pacific Time (PT)",
        industries: ["Technology", "Software", "Manufacturing", "Research"]
    },
    {
        slug: "austin",
        name: "Austin",
        state: "Texas",
        stateCode: "TX",
        population: "960,000",
        knownFor: "music, tech startups, and government",
        businessScene: "fastest-growing tech ecosystem",
        techHub: true,
        region: "South",
        localKeyword: "Austin startup web development",
        uniqueFact: "Austin is known as the 'Live Music Capital of the World'.",
        nearbyCity: "San Antonio",
        nearbyCitySlug: "san-antonio",
        timezone: "Central Time (CT)",
        industries: ["Technology", "Education", "Government", "Entertainment"]
    },
    {
        slug: "jacksonville",
        name: "Jacksonville",
        state: "Florida",
        stateCode: "FL",
        population: "950,000",
        knownFor: "logistics, finance, and tourism",
        businessScene: "growing Southeast business hub",
        techHub: false,
        region: "South",
        localKeyword: "Jacksonville web design",
        uniqueFact: "Jacksonville is the largest city by land area in the contiguous US.",
        nearbyCity: "Orlando",
        nearbyCitySlug: "orlando",
        timezone: "Eastern Time (ET)",
        industries: ["Logistics", "Finance", "Healthcare", "Tourism"]
    },
    {
        slug: "fort-worth",
        name: "Fort Worth",
        state: "Texas",
        stateCode: "TX",
        population: "930,000",
        knownFor: "livestock, aerospace, and energy",
        businessScene: "traditional and emerging industrial mix",
        techHub: false,
        region: "South",
        localKeyword: "Fort Worth web development",
        uniqueFact: "Fort Worth is home to the world's only twice-daily cattle drive.",
        nearbyCity: "Dallas",
        nearbyCitySlug: "dallas",
        timezone: "Central Time (CT)",
        industries: ["Aerospace", "Energy", "Transportation", "Healthcare"]
    },
    {
        slug: "columbus",
        name: "Columbus",
        state: "Ohio",
        stateCode: "OH",
        population: "900,000",
        knownFor: "education, government, and retail",
        businessScene: "steady and diverse regional market",
        techHub: false,
        region: "Midwest",
        localKeyword: "Columbus web services",
        uniqueFact: "Columbus is home to the world's largest private research institute.",
        nearbyCity: "Cleveland",
        nearbyCitySlug: "cleveland",
        timezone: "Eastern Time (ET)",
        industries: ["Education", "Retail", "Government", "Finance"]
    },
    {
        slug: "charlotte",
        name: "Charlotte",
        state: "North Carolina",
        stateCode: "NC",
        population: "870,000",
        knownFor: "banking, energy, and transportation",
        businessScene: "second-largest banking hub in the US",
        techHub: true,
        region: "South",
        localKeyword: "Charlotte fintech web development",
        uniqueFact: "Charlotte is home to the NASCAR Hall of Fame.",
        nearbyCity: "Raleigh",
        nearbyCitySlug: "raleigh",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Energy", "Transportation", "Motorsports"]
    },
    {
        slug: "indianapolis",
        name: "Indianapolis",
        state: "Indiana",
        stateCode: "IN",
        population: "860,000",
        knownFor: "sports, manufacturing, and pharma",
        businessScene: "major hub for distribution and life sciences",
        techHub: false,
        region: "Midwest",
        localKeyword: "Indianapolis web development",
        uniqueFact: "Indianapolis is the 'Amateur Sports Capital of the World'.",
        nearbyCity: "Cincinnati",
        nearbyCitySlug: "cincinnati",
        timezone: "Eastern Time (ET)",
        industries: ["Pharmaceuticals", "Manufacturing", "Sports", "Logistics"]
    },
    {
        slug: "san-francisco",
        name: "San Francisco",
        state: "California",
        stateCode: "CA",
        population: "815,000",
        knownFor: "tech, tourism, and finance",
        businessScene: "global leading tech hub",
        techHub: true,
        region: "West",
        localKeyword: "SF web development",
        uniqueFact: "The fortune cookie was invented in San Francisco.",
        nearbyCity: "Oakland",
        nearbyCitySlug: "oakland",
        timezone: "Pacific Time (PT)",
        industries: ["Technology", "Finance", "Tourism", "Research"]
    },
    {
        slug: "seattle",
        name: "Seattle",
        state: "Washington",
        stateCode: "WA",
        population: "730,000",
        knownFor: "cloud computing, ecommerce, and aerospace",
        businessScene: "innovative Pacific Northwest hub",
        techHub: true,
        region: "West",
        localKeyword: "Seattle cloud web services",
        uniqueFact: "Seattle is where the first Starbucks opened.",
        nearbyCity: "Tacoma",
        nearbyCitySlug: "tacoma",
        timezone: "Pacific Time (PT)",
        industries: ["Technology", "E-commerce", "Aerospace", "Biotechnology"]
    },
    {
        slug: "denver",
        name: "Denver",
        state: "Colorado",
        stateCode: "CO",
        population: "715,000",
        knownFor: "aerospace, tech, and energy",
        businessScene: "high-altitude innovation corridor",
        techHub: true,
        region: "West",
        localKeyword: "Denver web development",
        uniqueFact: "Denver is exactly one mile above sea level.",
        nearbyCity: "Aurora",
        nearbyCitySlug: "aurora",
        timezone: "Mountain Time (MT)",
        industries: ["Aerospace", "Technology", "Energy", "Tourism"]
    },
    {
        slug: "nashville",
        name: "Nashville",
        state: "Tennessee",
        stateCode: "TN",
        population: "690,000",
        knownFor: "music, healthcare, and higher education",
        businessScene: "booming healthcare and creative economy",
        techHub: false,
        region: "South",
        localKeyword: "Nashville web design",
        uniqueFact: "Nashville is known as the 'Music City'.",
        nearbyCity: "Knoxville",
        nearbyCitySlug: "knoxville",
        timezone: "Central Time (CT)",
        industries: ["Healthcare", "Music", "Education", "Tourism"]
    },
    {
        slug: "oklahoma-city",
        name: "Oklahoma City",
        state: "Oklahoma",
        stateCode: "OK",
        population: "680,000",
        knownFor: "energy, aircraft, and meat processing",
        businessScene: "diversifying economy with energy roots",
        techHub: false,
        region: "South",
        localKeyword: "OKC web services",
        uniqueFact: "OKC is home to one of the world's largest livestock markets.",
        nearbyCity: "Tulsa",
        nearbyCitySlug: "tulsa",
        timezone: "Central Time (CT)",
        industries: ["Energy", "Aerospace", "Manufacturing", "Healthcare"]
    },
    {
        slug: "las-vegas",
        name: "Las Vegas",
        state: "Nevada",
        stateCode: "NV",
        population: "640,000",
        knownFor: "tourism, gaming, and hospitality",
        businessScene: "global tourism and entertainment market",
        techHub: false,
        region: "West",
        localKeyword: "Vegas web development",
        uniqueFact: "Las Vegas has more hotel rooms than any city in the world.",
        nearbyCity: "Henderson",
        nearbyCitySlug: "henderson",
        timezone: "Pacific Time (PT)",
        industries: ["Tourism", "Gaming", "Hospitality", "Entertainment"]
    },
    {
        slug: "portland",
        name: "Portland",
        state: "Oregon",
        stateCode: "OR",
        population: "640,000",
        knownFor: "tech, fashion, and sustainability",
        businessScene: "creative and environmentally conscious hub",
        techHub: true,
        region: "West",
        localKeyword: "Portland web development",
        uniqueFact: "Portland is home to the world's smallest park.",
        nearbyCity: "Spokane",
        nearbyCitySlug: "spokane",
        timezone: "Pacific Time (PT)",
        industries: ["Technology", "Apparel", "Manufacturing", "Tourism"]
    },
    {
        slug: "memphis",
        name: "Memphis",
        state: "Tennessee",
        stateCode: "TN",
        population: "630,000",
        knownFor: "logistics, music, and agriculture",
        businessScene: "major distribution and supply chain hub",
        techHub: false,
        region: "South",
        localKeyword: "Memphis logistics IT",
        uniqueFact: "Memphis is the birthplace of Rock 'n' Roll.",
        nearbyCity: "Nashville",
        nearbyCitySlug: "nashville",
        timezone: "Central Time (CT)",
        industries: ["Logistics", "Transportation", "Manufacturing", "Healthcare"]
    },
    {
        slug: "louisville",
        name: "Louisville",
        state: "Kentucky",
        stateCode: "KY",
        population: "615,000",
        knownFor: "logistics, healthcare, and horses",
        businessScene: "growing regional hub for healthcare and aging care",
        techHub: false,
        region: "South",
        localKeyword: "Louisville web design",
        uniqueFact: "Louisville is where 90% of the world's disco balls are made.",
        nearbyCity: "Lexington",
        nearbyCitySlug: "lexington",
        timezone: "Eastern Time (ET)",
        industries: ["Logistics", "Healthcare", "Manufacturing", "Energy"]
    },
    {
        slug: "baltimore",
        name: "Baltimore",
        state: "Maryland",
        stateCode: "MD",
        population: "585,000",
        knownFor: "health, research, and port services",
        businessScene: "strong health and tech heritage",
        techHub: true,
        region: "Northeast",
        localKeyword: "Baltimore biotech web dev",
        uniqueFact: "Baltimore is the birthplace of the national anthem.",
        nearbyCity: "Philadelphia",
        nearbyCitySlug: "philadelphia",
        timezone: "Eastern Time (ET)",
        industries: ["Healthcare", "Port Services", "Manufacturing", "Education"]
    },
    {
        slug: "milwaukee",
        name: "Milwaukee",
        state: "Wisconsin",
        stateCode: "WI",
        population: "575,000",
        knownFor: "healthcare, manufacturing, and breweries",
        businessScene: "diverse and resilient industrial market",
        techHub: false,
        region: "Midwest",
        localKeyword: "Milwaukee industrial IT",
        uniqueFact: "Milwaukee is the 'Cream City' due to its distinct light-colored bricks.",
        nearbyCity: "Chicago",
        nearbyCitySlug: "chicago",
        timezone: "Central Time (CT)",
        industries: ["Manufacturing", "Healthcare", "Finance", "Food Processing"]
    },
    {
        slug: "albuquerque",
        name: "Albuquerque",
        state: "New Mexico",
        stateCode: "NM",
        population: "560,000",
        knownFor: "research, defense, and tourism",
        businessScene: "innovation in aerospace and national security",
        techHub: false,
        region: "West",
        localKeyword: "ABQ web development",
        uniqueFact: "Albuquerque is the hot air balloon capital of the world.",
        nearbyCity: "Tucson",
        nearbyCitySlug: "tucson",
        timezone: "Mountain Time (MT)",
        industries: ["Aerospace", "Defense", "Energy", "Education"]
    },
    {
        slug: "tucson",
        name: "Tucson",
        state: "Arizona",
        stateCode: "AZ",
        population: "540,000",
        knownFor: "optics, aerospace, and defense",
        businessScene: "specialized tech and medical hub",
        techHub: false,
        region: "West",
        localKeyword: "Tucson web services",
        uniqueFact: "Tucson is the oldest continuously inhabited settlement in the US.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Optics", "Aerospace", "Defense", "Health Services"]
    },
    {
        slug: "fresno",
        name: "Fresno",
        state: "California",
        stateCode: "CA",
        population: "540,000",
        knownFor: "agriculture, manufacturing, and healthcare",
        businessScene: "central valley agricultural hub",
        techHub: false,
        region: "West",
        localKeyword: "Fresno web design",
        uniqueFact: "Fresno is the raisin capital of the world.",
        nearbyCity: "Sacramento",
        nearbyCitySlug: "sacramento",
        timezone: "Pacific Time (PT)",
        industries: ["Agriculture", "Manufacturing", "Healthcare", "Transportation"]
    },
    {
        slug: "sacramento",
        name: "Sacramento",
        state: "California",
        stateCode: "CA",
        population: "525,000",
        knownFor: "government, healthcare, and education",
        businessScene: "steadily growing state capital market",
        techHub: false,
        region: "West",
        localKeyword: "Sacramento web development",
        uniqueFact: "Sacramento is the 'Indie Music Capital' of the West.",
        nearbyCity: "San Jose",
        nearbyCitySlug: "san-jose",
        timezone: "Pacific Time (PT)",
        industries: ["Government", "Healthcare", "Education", "Agriculture"]
    },
    {
        slug: "atlanta",
        name: "Atlanta",
        state: "Georgia",
        stateCode: "GA",
        population: "500,000",
        knownFor: "logistics, media, and fintech",
        businessScene: "major hub for the Southeast and global brands",
        techHub: true,
        region: "South",
        localKeyword: "Atlanta fintech dev",
        uniqueFact: "Atlanta is known as the 'City in a Forest'.",
        nearbyCity: "Augusta",
        nearbyCitySlug: "augusta",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Logistics", "Media", "Healthcare"]
    },
    {
        slug: "miami",
        name: "Miami",
        state: "Florida",
        stateCode: "FL",
        population: "440,000",
        knownFor: "finance, tourism, and international trade",
        businessScene: "gateway to Latin America",
        techHub: true,
        region: "South",
        localKeyword: "Miami web design",
        uniqueFact: "Miami is the only major US city founded by a woman.",
        nearbyCity: "Fort Lauderdale",
        nearbyCitySlug: "fort-lauderdale",
        timezone: "Eastern Time (ET)",
        industries: ["Tourism", "Finance", "Trade", "Real Estate"]
    },
    {
        slug: "minneapolis",
        name: "Minneapolis",
        state: "Minnesota",
        stateCode: "MN",
        population: "430,000",
        knownFor: "retail, health, and finance",
        businessScene: "diverse and innovative northern market",
        techHub: true,
        region: "Midwest",
        localKeyword: "Minneapolis web development",
        uniqueFact: "Minneapolis has more golfers per capita than any other city.",
        nearbyCity: "St. Paul",
        nearbyCitySlug: "st-paul",
        timezone: "Central Time (CT)",
        industries: ["Retail", "Healthcare", "Finance", "Manufacturing"]
    },
    {
        slug: "tampa",
        name: "Tampa",
        state: "Florida",
        stateCode: "FL",
        population: "385,000",
        knownFor: "finance, tourism, and military",
        businessScene: "vibrant Gulf Coast business climate",
        techHub: false,
        region: "South",
        localKeyword: "Tampa web services",
        uniqueFact: "Tampa is the lightning capital of North America.",
        nearbyCity: "Orlando",
        nearbyCitySlug: "orlando",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Healthcare", "Tourism", "Military"]
    },
    {
        slug: "new-orleans",
        name: "New Orleans",
        state: "Louisiana",
        stateCode: "LA",
        population: "380,000",
        knownFor: "culture, tourism, and port activities",
        businessScene: "creative and historically rich port economy",
        techHub: false,
        region: "South",
        localKeyword: "NOLA web development",
        uniqueFact: "New Orleans is the birthplace of Jazz.",
        nearbyCity: "Houston",
        nearbyCitySlug: "houston",
        timezone: "Central Time (CT)",
        industries: ["Tourism", "Port Services", "Oil and Gas", "Healthcare"]
    },
    {
        slug: "cleveland",
        name: "Cleveland",
        state: "Ohio",
        stateCode: "OH",
        population: "370,000",
        knownFor: "healthcare, manufacturing, and tech",
        businessScene: "reinvention focused on innovation",
        techHub: false,
        region: "Midwest",
        localKeyword: "Cleveland web design",
        uniqueFact: "Cleveland is home to the Rock and Roll Hall of Fame.",
        nearbyCity: "Akron",
        nearbyCitySlug: "akron",
        timezone: "Eastern Time (ET)",
        industries: ["Healthcare", "Manufacturing", "Finance", "Education"]
    },
    {
        slug: "raleigh",
        name: "Raleigh",
        state: "North Carolina",
        stateCode: "NC",
        population: "470,000",
        knownFor: "tech, healthcare, and research",
        businessScene: "innovation heart of the Research Triangle",
        techHub: true,
        region: "South",
        localKeyword: "Raleigh biotech web dev",
        uniqueFact: "Raleigh is known as the 'City of Oaks'.",
        nearbyCity: "Durham",
        nearbyCitySlug: "durham",
        timezone: "Eastern Time (ET)",
        industries: ["Technology", "Healthcare", "Research", "Education"]
    },
    {
        slug: "virginia-beach",
        name: "Virginia Beach",
        state: "Virginia",
        stateCode: "VA",
        population: "460,000",
        knownFor: "tourism, military, and agriculture",
        businessScene: "stable coastal and defense market",
        techHub: false,
        region: "South",
        localKeyword: "Virginia Beach web dev",
        uniqueFact: "Virginia Beach has the world's longest pleasure beach.",
        nearbyCity: "Norfolk",
        nearbyCitySlug: "norfolk",
        timezone: "Eastern Time (ET)",
        industries: ["Tourism", "Military", "Agriculture", "Real Estate"]
    },
    {
        slug: "colorado-springs",
        name: "Colorado Springs",
        state: "Colorado",
        stateCode: "CO",
        population: "480,000",
        knownFor: "military, tech, and tourism",
        businessScene: "high-altitude tech and defense hub",
        techHub: false,
        region: "West",
        localKeyword: "Colorado Springs web services",
        uniqueFact: "Colorado Springs is home to the US Olympic Committee.",
        nearbyCity: "Denver",
        nearbyCitySlug: "denver",
        timezone: "Mountain Time (MT)",
        industries: ["Military", "Technology", "Tourism", "Education"]
    },
    {
        slug: "orlando",
        name: "Orlando",
        state: "Florida",
        stateCode: "FL",
        population: "305,000",
        knownFor: "tourism, entertainment, and aerospace",
        businessScene: "global leading tourism market",
        techHub: false,
        region: "South",
        localKeyword: "Orlando web design",
        uniqueFact: "Orlando is the most visited city in the world.",
        nearbyCity: "Tampa",
        nearbyCitySlug: "tampa",
        timezone: "Eastern Time (ET)",
        industries: ["Tourism", "Entertainment", "Aerospace", "Technology"]
    },
    {
        slug: "arlington",
        name: "Arlington",
        state: "Texas",
        stateCode: "TX",
        population: "400,000",
        knownFor: "entertainment, aerospace, and manufacturing",
        businessScene: "sports and recreation hub",
        techHub: false,
        region: "South",
        localKeyword: "Arlington web services",
        uniqueFact: "Arlington is home to the AT&T Stadium.",
        nearbyCity: "Fort Worth",
        nearbyCitySlug: "fort-worth",
        timezone: "Central Time (CT)",
        industries: ["Entertainment", "Aerospace", "Manufacturing", "Tourism"]
    },
    {
        slug: "pittsburgh",
        name: "Pittsburgh",
        state: "Pennsylvania",
        stateCode: "PA",
        population: "300,000",
        knownFor: "tech, healthcare, and education",
        businessScene: "renaissance city focused on innovation",
        techHub: true,
        region: "Northeast",
        localKeyword: "Pittsburgh robotics dev",
        uniqueFact: "Pittsburgh is known as the 'Steel City'.",
        nearbyCity: "Cleveland",
        nearbyCitySlug: "cleveland",
        timezone: "Eastern Time (ET)",
        industries: ["Technology", "Healthcare", "Education", "Manufacturing"]
    },
    {
        slug: "st-louis",
        name: "St. Louis",
        state: "Missouri",
        stateCode: "MO",
        population: "300,000",
        knownFor: "healthcare, pharma, and finance",
        businessScene: "historically stable regional hub",
        techHub: false,
        region: "Midwest",
        localKeyword: "St. Louis web services",
        uniqueFact: "The ice cream cone was popularized at the 1904 St. Louis World's Fair.",
        nearbyCity: "Cincinnati",
        nearbyCitySlug: "cincinnati",
        timezone: "Central Time (CT)",
        industries: ["Healthcare", "Manufacturing", "Finance", "Education"]
    },
    {
        slug: "cincinnati",
        name: "Cincinnati",
        state: "Ohio",
        stateCode: "OH",
        population: "310,000",
        knownFor: "manufacturing, finance, and consumer goods",
        businessScene: "established corporate base",
        techHub: false,
        region: "Midwest",
        localKeyword: "Cincinnati web design",
        uniqueFact: "Cincinnati was the first city in the world to have a professional fire department.",
        nearbyCity: "Indianapolis",
        nearbyCitySlug: "indianapolis",
        timezone: "Eastern Time (ET)",
        industries: ["Manufacturing", "Finance", "Retail", "Healthcare"]
    },
    {
        slug: "riverside",
        name: "Riverside",
        state: "California",
        stateCode: "CA",
        population: "330,000",
        knownFor: "education, manufacturing, and logistics",
        businessScene: "inland industrial and educational hub",
        techHub: false,
        region: "West",
        localKeyword: "Riverside web dev",
        uniqueFact: "Riverside is the birthplace of the California citrus industry.",
        nearbyCity: "San Bernardino",
        nearbyCitySlug: "san-bernardino",
        timezone: "Pacific Time (PT)",
        industries: ["Education", "Manufacturing", "Logistics", "Retail"]
    },
    {
        slug: "lexington",
        name: "Lexington",
        state: "Kentucky",
        stateCode: "KY",
        population: "320,000",
        knownFor: "education, healthcare, and horses",
        businessScene: "stable college-town economy",
        techHub: false,
        region: "South",
        localKeyword: "Lexington web design",
        uniqueFact: "Lexington is the horse capital of the world.",
        nearbyCity: "Louisville",
        nearbyCitySlug: "louisville",
        timezone: "Eastern Time (ET)",
        industries: ["Education", "Healthcare", "Manufacturing", "Tourism"]
    },
    {
        slug: "anchorage",
        name: "Anchorage",
        state: "Alaska",
        stateCode: "AK",
        population: "290,000",
        knownFor: "oil, transport, and tourism",
        businessScene: "major northern logistics point",
        techHub: false,
        region: "West",
        localKeyword: "Anchorage web dev",
        uniqueFact: "Anchorage is within 10 hours by air to 90% of the industrialized world.",
        nearbyCity: "Seattle",
        nearbyCitySlug: "seattle",
        timezone: "Alaska Time (AKT)",
        industries: ["Oil and Gas", "Transportation", "Tourism", "Military"]
    },
    {
        slug: "stockton",
        name: "Stockton",
        state: "California",
        stateCode: "CA",
        population: "320,000",
        knownFor: "agriculture, logistics, and healthcare",
        businessScene: "central valley multimodal hub",
        techHub: false,
        region: "West",
        localKeyword: "Stockton web service",
        uniqueFact: "Stockton is the first city in California to have a name not of Spanish or Native American origin.",
        nearbyCity: "Sacramento",
        nearbyCitySlug: "sacramento",
        timezone: "Pacific Time (PT)",
        industries: ["Agriculture", "Logistics", "Healthcare", "Manufacturing"]
    },
    {
        slug: "st-paul",
        name: "St. Paul",
        state: "Minnesota",
        stateCode: "MN",
        population: "310,000",
        knownFor: "government, health, and manufacturing",
        businessScene: "stable state capital market",
        techHub: false,
        region: "Midwest",
        localKeyword: "St. Paul web dev",
        uniqueFact: "St. Paul has more shoreline than any other city along the Mississippi River.",
        nearbyCity: "Minneapolis",
        nearbyCitySlug: "minneapolis",
        timezone: "Central Time (CT)",
        industries: ["Government", "Healthcare", "Manufacturing", "Insurance"]
    },
    {
        slug: "newark",
        name: "Newark",
        state: "New Jersey",
        stateCode: "NJ",
        population: "310,000",
        knownFor: "transport, finance, and health",
        businessScene: "major Northeast distribution hub",
        techHub: false,
        region: "Northeast",
        localKeyword: "Newark web design",
        uniqueFact: "Newark is one of the oldest cities in the US.",
        nearbyCity: "Jersey City",
        nearbyCitySlug: "jersey-city",
        timezone: "Eastern Time (ET)",
        industries: ["Logistics", "Finance", "Insurance", "Healthcare"]
    },
    {
        slug: "greensboro",
        name: "Greensboro",
        state: "North Carolina",
        stateCode: "NC",
        population: "300,000",
        knownFor: "transport, textile, and education",
        businessScene: "growing regional logistics market",
        techHub: false,
        region: "South",
        localKeyword: "Greensboro web services",
        uniqueFact: "Greensboro is home to the largest hotel in North Carolina.",
        nearbyCity: "Winston-Salem",
        nearbyCitySlug: "winston-salem",
        timezone: "Eastern Time (ET)",
        industries: ["Manufacturing", "Education", "Healthcare", "Transportation"]
    },
    {
        slug: "buffalo",
        name: "Buffalo",
        state: "New York",
        stateCode: "NY",
        population: "280,000",
        knownFor: "manufacturing, education, and healthcare",
        businessScene: "revitalizing industrial economy",
        techHub: false,
        region: "Northeast",
        localKeyword: "Buffalo web development",
        uniqueFact: "Buffalo is known as the 'City of Good Neighbors'.",
        nearbyCity: "Rochester",
        nearbyCitySlug: "rochester",
        timezone: "Eastern Time (ET)",
        industries: ["Healthcare", "Manufacturing", "Education", "Retail"]
    },
    {
        slug: "plano",
        name: "Plano",
        state: "Texas",
        stateCode: "TX",
        population: "290,000",
        knownFor: "tech, finance, and corporate headquarters",
        businessScene: "major corporate and tech hub",
        techHub: true,
        region: "South",
        localKeyword: "Plano IT services",
        uniqueFact: "Plano is home to several major multi-national corporations.",
        nearbyCity: "Dallas",
        nearbyCitySlug: "dallas",
        timezone: "Central Time (CT)",
        industries: ["Technology", "Finance", "Retailing", "Telecom"]
    },
    {
        slug: "henderson",
        name: "Henderson",
        state: "Nevada",
        stateCode: "NV",
        population: "320,000",
        knownFor: "research, tech, and healthcare",
        businessScene: "fast-growing high-tech market",
        techHub: false,
        region: "West",
        localKeyword: "Henderson web dev",
        uniqueFact: "Henderson is the second-largest city in Nevada.",
        nearbyCity: "Las Vegas",
        nearbyCitySlug: "las-vegas",
        timezone: "Pacific Time (PT)",
        industries: ["Technology", "Healthcare", "Research", "Hospitality"]
    },
    {
        slug: "lincoln",
        name: "Lincoln",
        state: "Nebraska",
        stateCode: "NE",
        population: "295,000",
        knownFor: "education, government, and healthcare",
        businessScene: "stable college and state capital town",
        techHub: false,
        region: "Midwest",
        localKeyword: "Lincoln web design",
        uniqueFact: "Lincoln is the state capital of Nebraska.",
        nearbyCity: "Omaha",
        nearbyCitySlug: "omaha",
        timezone: "Central Time (CT)",
        industries: ["Education", "Government", "Healthcare", "Finance"]
    },
    {
        slug: "durham",
        name: "Durham",
        state: "North Carolina",
        stateCode: "NC",
        population: "285,000",
        knownFor: "medtech, research, and education",
        businessScene: "innovation heart of the RTP",
        techHub: true,
        region: "South",
        localKeyword: "Durham biotech dev",
        uniqueFact: "Durham is the home of Duke University.",
        nearbyCity: "Raleigh",
        nearbyCitySlug: "raleigh",
        timezone: "Eastern Time (ET)",
        industries: ["Healthcare", "Research", "Technology", "Education"]
    },
    {
        slug: "jersey-city",
        name: "Jersey City",
        state: "New Jersey",
        stateCode: "NJ",
        population: "290,000",
        knownFor: "finance, transport, and tech",
        businessScene: "major Northeast financial center",
        techHub: true,
        region: "Northeast",
        localKeyword: "Jersey City fintech dev",
        uniqueFact: "Jersey City is the most diverse city in the US.",
        nearbyCity: "New York City",
        nearbyCitySlug: "new-york-city",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Insurance", "Logistics", "Technology"]
    },
    {
        slug: "chandler",
        name: "Chandler",
        state: "Arizona",
        stateCode: "AZ",
        population: "275,000",
        knownFor: "high-tech and manufacturing",
        businessScene: "growing tech hub in the Southwest",
        techHub: true,
        region: "West",
        localKeyword: "Chandler tech dev",
        uniqueFact: "Chandler is home to several high-tech manufacturing plants.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Technology", "Manufacturing", "Research", "Education"]
    },
    {
        slug: "madison",
        name: "Madison",
        state: "Wisconsin",
        stateCode: "WI",
        population: "270,000",
        knownFor: "education, government, and biotech",
        businessScene: "thriving innovative hub",
        techHub: true,
        region: "Midwest",
        localKeyword: "Madison biotech dev",
        uniqueFact: "Madison is built on an isthmus between two lakes.",
        nearbyCity: "Milwaukee",
        nearbyCitySlug: "milwaukee",
        timezone: "Central Time (CT)",
        industries: ["Education", "Government", "Biotechnology", "Healthcare"]
    },
    {
        slug: "lubbock",
        name: "Lubbock",
        state: "Texas",
        stateCode: "TX",
        population: "260,000",
        knownFor: "agriculture, health, and education",
        businessScene: "heart of the Texas high plains",
        techHub: false,
        region: "South",
        localKeyword: "Lubbock web design",
        uniqueFact: "Lubbock is the birthplace of Buddy Holly.",
        nearbyCity: "Amarillo",
        nearbyCitySlug: "amarillo",
        timezone: "Central Time (CT)",
        industries: ["Agriculture", "Education", "Healthcare", "Manufacturing"]
    },
    {
        slug: "norfolk",
        name: "Norfolk",
        state: "Virginia",
        stateCode: "VA",
        population: "240,000",
        knownFor: "military, port, and transport",
        businessScene: "major maritime and military hub",
        techHub: false,
        region: "South",
        localKeyword: "Norfolk maritime IT",
        uniqueFact: "Norfolk is home to the world's largest naval base.",
        nearbyCity: "Virginia Beach",
        nearbyCitySlug: "virginia-beach",
        timezone: "Eastern Time (ET)",
        industries: ["Military", "Maritme", "Logistics", "Healthcare"]
    },
    {
        slug: "winston-salem",
        name: "Winston-Salem",
        state: "North Carolina",
        stateCode: "NC",
        population: "250,000",
        knownFor: "education, healthcare, and finance",
        businessScene: "stable and evolving Southern market",
        techHub: false,
        region: "South",
        localKeyword: "Winston-Salem web design",
        uniqueFact: "Winston-Salem is home to the headquarters of Krispy Kreme.",
        nearbyCity: "Greensboro",
        nearbyCitySlug: "greensboro",
        timezone: "Eastern Time (ET)",
        industries: ["Education", "Healthcare", "Finance", "Retail"]
    },
    {
        slug: "garland",
        name: "Garland",
        state: "Texas",
        stateCode: "TX",
        population: "245,000",
        knownFor: "manufacturing, transport, and retail",
        businessScene: "diverse Northeast Texas industrial hub",
        techHub: false,
        region: "South",
        localKeyword: "Garland web services",
        uniqueFact: "Garland is home to over 300 manufacturers.",
        nearbyCity: "Dallas",
        nearbyCitySlug: "dallas",
        timezone: "Central Time (CT)",
        industries: ["Manufacturing", "Transportation", "Retail", "Healthcare"]
    },
    {
        slug: "boise",
        name: "Boise",
        state: "Idaho",
        stateCode: "ID",
        population: "235,000",
        knownFor: "tech, healthcare, and education",
        businessScene: "innovation-driven Western market",
        techHub: true,
        region: "West",
        localKeyword: "Boise web development",
        uniqueFact: "Boise is known as the 'City of Trees'.",
        nearbyCity: "Spokane",
        nearbyCitySlug: "spokane",
        timezone: "Mountain Time (MT)",
        industries: ["Technology", "Healthcare", "Education", "Agriculture"]
    },
    {
        slug: "scottsdale",
        name: "Scottsdale",
        state: "Arizona",
        stateCode: "AZ",
        population: "250,000",
        knownFor: "tourism, healthcare, and research",
        businessScene: "high-end business and retail hub",
        techHub: false,
        region: "West",
        localKeyword: "Scottsdale web design",
        uniqueFact: "Scottsdale is known as 'The West's Most Western Town'.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Tourism", "Healthcare", "Research", "Retail"]
    },
    {
        slug: "birmingham",
        name: "Birmingham",
        state: "Alabama",
        stateCode: "AL",
        population: "210,000",
        knownFor: "healthcare, finance, and manufacturing",
        businessScene: "growing regional market",
        techHub: false,
        region: "South",
        localKeyword: "Birmingham web services",
        uniqueFact: "Birmingham is the only place in the world where three elements needed to make iron are found in close proximity.",
        nearbyCity: "Huntsville",
        nearbyCitySlug: "huntsville",
        timezone: "Central Time (CT)",
        industries: ["Healthcare", "Finance", "Manufacturing", "Mining"]
    },
    {
        slug: "rochester",
        name: "Rochester",
        state: "New York",
        stateCode: "NY",
        population: "210,000",
        knownFor: "optics, education, and health",
        businessScene: "innovation-driven lakefront market",
        techHub: true,
        region: "Northeast",
        localKeyword: "Rochester optics dev",
        uniqueFact: "Rochester is known as the 'Flower City'.",
        nearbyCity: "Buffalo",
        nearbyCitySlug: "buffalo",
        timezone: "Eastern Time (ET)",
        industries: ["Optics", "Education", "Healthcare", "Manufacturing"]
    },
    {
        slug: "richmond",
        name: "Richmond",
        state: "Virginia",
        stateCode: "VA",
        population: "230,000",
        knownFor: "finance, health, and education",
        businessScene: "historically stable state capital market",
        techHub: false,
        region: "South",
        localKeyword: "Richmond web design",
        uniqueFact: "Richmond is one of the oldest US cities.",
        nearbyCity: "Norfolk",
        nearbyCitySlug: "norfolk",
        timezone: "Eastern Time (ET)",
        industries: ["Finance", "Healthcare", "Education", "Government"]
    },
    {
        slug: "des-moines",
        name: "Des Moines",
        state: "Iowa",
        stateCode: "IA",
        population: "215,000",
        knownFor: "insurance, agricuture, and manufacturing",
        businessScene: "stable Midwest financial center",
        techHub: false,
        region: "Midwest",
        localKeyword: "Des Moines insuretech",
        uniqueFact: "Des Moines is known as the 'Hartford of the West' for its insurance presence.",
        nearbyCity: "Omaha",
        nearbyCitySlug: "omaha",
        timezone: "Central Time (CT)",
        industries: ["Insurance", "Agriculture", "Manufacturing", "Healthcare"]
    },
    {
        slug: "spokane",
        name: "Spokane",
        state: "Washington",
        stateCode: "WA",
        population: "230,000",
        knownFor: "healthcare, manufacturing, and transport",
        businessScene: "regional Inland Northwest hub",
        techHub: false,
        region: "West",
        localKeyword: "Spokane web dev",
        uniqueFact: "Spokane is where Father's Day was founded.",
        nearbyCity: "Boise",
        nearbyCitySlug: "boise",
        timezone: "Pacific Time (PT)",
        industries: ["Healthcare", "Manufacturing", "Transportation", "Education"]
    },
    {
        slug: "tacoma",
        name: "Tacoma",
        state: "Washington",
        stateCode: "WA",
        population: "220,000",
        knownFor: "transport, port services, and healthcare",
        businessScene: "major Northwest maritime and industrial market",
        techHub: false,
        region: "West",
        localKeyword: "Tacoma maritime dev",
        uniqueFact: "Tacoma is known as the 'City of Destiny'.",
        nearbyCity: "Seattle",
        nearbyCitySlug: "seattle",
        timezone: "Pacific Time (PT)",
        industries: ["Transportation", "Maritime", "Healthcare", "Manufacturing"]
    },
    {
        slug: "salt-lake-city",
        name: "Salt Lake City",
        state: "Utah",
        stateCode: "UT",
        population: "200,000",
        knownFor: "tech, tourism, and research",
        businessScene: "leading Western tech and finance market",
        techHub: true,
        region: "West",
        localKeyword: "SLC tech dev",
        uniqueFact: "SLC hosted the 2002 Winter Olympics.",
        nearbyCity: "Boise",
        nearbyCitySlug: "boise",
        timezone: "Mountain Time (MT)",
        industries: ["Technology", "Tourism", "Education", "Finance"]
    },
    {
        slug: "augusta",
        name: "Augusta",
        state: "Georgia",
        stateCode: "GA",
        population: "200,000",
        knownFor: "military, healthcare, and education",
        businessScene: "diverse and stable Southeast hub",
        techHub: false,
        region: "South",
        localKeyword: "Augusta web services",
        uniqueFact: "Augusta is home to the Masters golf tournament.",
        nearbyCity: "Atlanta",
        nearbyCitySlug: "atlanta",
        timezone: "Eastern Time (ET)",
        industries: ["Military", "Healthcare", "Education", "Manufacturing"]
    },
    {
        slug: "huntsville",
        name: "Huntsville",
        state: "Alabama",
        stateCode: "AL",
        population: "215,000",
        knownFor: "aerospace, military, and research",
        businessScene: "growing Southern tech hub",
        techHub: true,
        region: "South",
        localKeyword: "Huntsville aerospace dev",
        uniqueFact: "Huntsville is known as 'Rocket City'.",
        nearbyCity: "Birmingham",
        nearbyCitySlug: "birmingham",
        timezone: "Central Time (CT)",
        industries: ["Aerospace", "Military", "Research", "Education"]
    },
    {
        slug: "knoxville",
        name: "Knoxville",
        state: "Tennessee",
        stateCode: "TN",
        population: "190,000",
        knownFor: "research, education, and transport",
        businessScene: "Eastern Tennessee innovation hub",
        techHub: false,
        region: "South",
        localKeyword: "Knoxville web design",
        uniqueFact: "Knoxville hosted the 1982 World's Fair.",
        nearbyCity: "Nashville",
        nearbyCitySlug: "nashville",
        timezone: "Eastern Time (ET)",
        industries: ["Research", "Education", "Transportation", "Tourism"]
    },
    {
        slug: "providence",
        name: "Providence",
        state: "Rhode Island",
        stateCode: "RI",
        population: "190,000",
        knownFor: "education, health, and jewelry",
        businessScene: "creative and educational heart of RI",
        techHub: false,
        region: "Northeast",
        localKeyword: "Providence web dev",
        uniqueFact: "Providence has more coffee and doughnut shops per capita than any other city in the country.",
        nearbyCity: "Hartford",
        nearbyCitySlug: "hartford",
        timezone: "Eastern Time (ET)",
        industries: ["Education", "Healthcare", "Jewelry", "Financial Services"]
    },
    {
        slug: "hartford",
        name: "Hartford",
        state: "Connecticut",
        stateCode: "CT",
        population: "120,000",
        knownFor: "insurance, healthcare, and manufacturing",
        businessScene: "world capital of insurance",
        techHub: false,
        region: "Northeast",
        localKeyword: "Hartford insuretech",
        uniqueFact: "Hartford is the insurance capital of the world.",
        nearbyCity: "Providence",
        nearbyCitySlug: "providence",
        timezone: "Eastern Time (ET)",
        industries: ["Insurance", "Healthcare", "Manufacturing", "Finance"]
    },
    {
        slug: "bakersfield",
        name: "Bakersfield",
        state: "California",
        stateCode: "CA",
        population: "400,000",
        knownFor: "agriculture, oil, and transport",
        businessScene: "major Central Valley industrial market",
        techHub: false,
        region: "West",
        localKeyword: "Bakersfield web services",
        uniqueFact: "Bakersfield is known as the 'Country Music Capital of the West Coast'.",
        nearbyCity: "Stockton",
        nearbyCitySlug: "stockton",
        timezone: "Pacific Time (PT)",
        industries: ["Agriculture", "Oil and Gas", "Transportation", "Education"]
    },
    {
        slug: "tempe",
        name: "Tempe",
        state: "Arizona",
        stateCode: "AZ",
        population: "185,000",
        knownFor: "education, tech, and retail",
        businessScene: "vibrant college-town tech hub",
        techHub: true,
        region: "West",
        localKeyword: "Tempe tech dev",
        uniqueFact: "Tempe is home to Arizona State University.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Education", "Technology", "Retail", "Research"]
    },
    {
        slug: "fort-lauderdale",
        name: "Fort Lauderdale",
        state: "Florida",
        stateCode: "FL",
        population: "185,000",
        knownFor: "tourism, yachting, and transport",
        businessScene: "high-end maritime market",
        techHub: false,
        region: "South",
        localKeyword: "Fort Lauderdale web design",
        uniqueFact: "Fort Lauderdale is known as the 'Venice of America'.",
        nearbyCity: "Miami",
        nearbyCitySlug: "miami",
        timezone: "Eastern Time (ET)",
        industries: ["Tourism", "Maritime", "Transportation", "Real Estate"]
    },
    {
        slug: "glendale",
        name: "Glendale",
        state: "Arizona",
        stateCode: "AZ",
        population: "250,000",
        knownFor: "entertainment, health, and transport",
        businessScene: "growing West Valley hub",
        techHub: false,
        region: "West",
        localKeyword: "Glendale web services",
        uniqueFact: "Glendale is home to several major sports venues.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Entertainment", "Healthcare", "Transportation", "Retail"]
    },
    {
        slug: "akron",
        name: "Akron",
        state: "Ohio",
        stateCode: "OH",
        population: "190,000",
        knownFor: "manufacturing, research, and education",
        businessScene: "innovation heart of polymer science",
        techHub: false,
        region: "Midwest",
        localKeyword: "Akron polymer tech",
        uniqueFact: "Akron is the 'Rubber Capital of the World'.",
        nearbyCity: "Cleveland",
        nearbyCitySlug: "cleveland",
        timezone: "Eastern Time (ET)",
        industries: ["Manufacturing", "Research", "Education", "Healthcare"]
    },
    {
        slug: "aurora",
        name: "Aurora",
        state: "Colorado",
        stateCode: "CO",
        population: "390,000",
        knownFor: "military, healthcare, and education",
        businessScene: "stable and diverse regional hub",
        techHub: false,
        region: "West",
        localKeyword: "Aurora web services",
        uniqueFact: "Aurora is the third-largest city in Colorado.",
        nearbyCity: "Denver",
        nearbyCitySlug: "denver",
        timezone: "Mountain Time (MT)",
        industries: ["Military", "Healthcare", "Education", "Retail"]
    },
    {
        slug: "santa-ana",
        name: "Santa Ana",
        state: "California",
        stateCode: "CA",
        population: "310,000",
        knownFor: "education, health, and retail",
        businessScene: "vibrant Orange County hub",
        techHub: false,
        region: "West",
        localKeyword: "Santa Ana web design",
        uniqueFact: "Santa Ana is the second-largest city in Orange County.",
        nearbyCity: "Long Beach",
        nearbyCitySlug: "long-beach",
        timezone: "Pacific Time (PT)",
        industries: ["Education", "Healthcare", "Retail", "Government"]
    },
    {
        slug: "corpus-christi",
        name: "Corpus Christi",
        state: "Texas",
        stateCode: "TX",
        population: "320,000",
        knownFor: "oil, port, and tourism",
        businessScene: "major Gulf Coast industrial port",
        techHub: false,
        region: "South",
        localKeyword: "Corpus Christi maritime IT",
        uniqueFact: "Corpus Christi is known as the 'Sparkling City by the Sea'.",
        nearbyCity: "San Antonio",
        nearbyCitySlug: "san-antonio",
        timezone: "Central Time (CT)",
        industries: ["Oil and Gas", "Port Services", "Tourism", "Military"]
    },
    {
        slug: "kansas-city-mo",
        name: "Kansas City",
        state: "Missouri",
        stateCode: "MO",
        population: "510,000",
        knownFor: "manufacturing, transport, and finance",
        businessScene: "major Midwest business and creative hub",
        techHub: true,
        region: "Midwest",
        localKeyword: "Kansas City web design",
        uniqueFact: "Kansas City has more fountains than any city in the world besides Rome.",
        nearbyCity: "Kansas City KS",
        nearbyCitySlug: "kansas-city-ks",
        timezone: "Central Time (CT)",
        industries: ["Manufacturing", "Transportation", "Finance", "Healthcare"]
    },
    {
        slug: "kansas-city-ks",
        name: "Kansas City",
        state: "Kansas",
        stateCode: "KS",
        population: "155,000",
        knownFor: "manufacturing, logistics, and education",
        businessScene: "integrated and evolving gateway market",
        techHub: false,
        region: "Midwest",
        localKeyword: "KCK logistics dev",
        uniqueFact: "The Wizard of Oz is set in Kansas.",
        nearbyCity: "Kansas City MO",
        nearbyCitySlug: "kansas-city-mo",
        timezone: "Central Time (CT)",
        industries: ["Manufacturing", "Logistics", "Education", "Healthcare"]
    },
    {
        slug: "omaha",
        name: "Omaha",
        state: "Nebraska",
        stateCode: "NE",
        population: "490,000",
        knownFor: "finance, transport, and manufacturing",
        businessScene: "major regional financial and corporate center",
        techHub: true,
        region: "Midwest",
        localKeyword: "Omaha finserve dev",
        uniqueFact: "Omaha is home to five Fortune 500 companies.",
        nearbyCity: "Lincoln",
        nearbyCitySlug: "lincoln",
        timezone: "Central Time (CT)",
        industries: ["Finance", "Insurance", "Transportation", "Manufacturing"]
    },
    {
        slug: "tulsa",
        name: "Tulsa",
        state: "Oklahoma",
        stateCode: "OK",
        population: "410,000",
        knownFor: "energy, aeronautics, and finance",
        businessScene: "innovation heart of the Oklahoma energy belt",
        techHub: false,
        region: "South",
        localKeyword: "Tulsa energy tech",
        uniqueFact: "Tulsa was once known as the 'Oil Capital of the World'.",
        nearbyCity: "Oklahoma City",
        nearbyCitySlug: "oklahoma-city",
        timezone: "Central Time (CT)",
        industries: ["Energy", "Aerospace", "Finance", "Healthcare"]
    },
    {
        slug: "el-paso",
        name: "El Paso",
        state: "Texas",
        stateCode: "TX",
        population: "680,000",
        knownFor: "government, education, and port services",
        businessScene: "major international trade and military hub",
        techHub: false,
        region: "South",
        localKeyword: "El Paso logisitcs dev",
        uniqueFact: "El Paso is the only major Texas city that uses Mountain Time.",
        nearbyCity: "Albuquerque",
        nearbyCitySlug: "albuquerque",
        timezone: "Mountain Time (MT)",
        industries: ["Military", "Education", "Trade", "Logistics"]
    },
    {
        slug: "mesa",
        name: "Mesa",
        state: "Arizona",
        stateCode: "AZ",
        population: "515,000",
        knownFor: "education, tech, and retail",
        businessScene: "vibrant and growing East Valley market",
        techHub: false,
        region: "West",
        localKeyword: "Mesa web services",
        uniqueFact: "Mesa is the largest suburban city in the US.",
        nearbyCity: "Phoenix",
        nearbyCitySlug: "phoenix",
        timezone: "Mountain Time (MT)",
        industries: ["Education", "Technology", "Retail", "Healthcare"]
    },
    {
        slug: "wichita",
        name: "Wichita",
        state: "Kansas",
        stateCode: "KS",
        population: "400,000",
        knownFor: "aerospace, manufacturing, and transport",
        businessScene: "world capital of aviation",
        techHub: false,
        region: "Midwest",
        localKeyword: "Wichita aerospace IT",
        uniqueFact: "Wichita is the 'Air Capital of the World'.",
        nearbyCity: "Kansas City MO",
        nearbyCitySlug: "kansas-city-mo",
        timezone: "Central Time (CT)",
        industries: ["Aerospace", "Manufacturing", "Energy", "Healthcare"]
    },
    {
        slug: "long-beach",
        name: "Long Beach",
        state: "California",
        stateCode: "CA",
        population: "460,000",
        knownFor: "port, aerospace, and education",
        businessScene: "major maritime and industrial gateway",
        techHub: false,
        region: "West",
        localKeyword: "Long Beach port dev",
        uniqueFact: "Long Beach is home to the world's most successful municipal aquarium.",
        nearbyCity: "Los Angeles",
        nearbyCitySlug: "los-angeles",
        timezone: "Pacific Time (PT)",
        industries: ["Maritime", "Aerospace", "Education", "Healthcare"]
    },
    {
        slug: "oakland",
        name: "Oakland",
        state: "California",
        stateCode: "CA",
        population: "435,000",
        knownFor: "port, transport, and tech",
        businessScene: "major innovative industrial heart",
        techHub: true,
        region: "West",
        localKeyword: "Oakland web dev",
        uniqueFact: "Oakland is the most diverse city in the US.",
        nearbyCity: "San Francisco",
        nearbyCitySlug: "san-francisco",
        timezone: "Pacific Time (PT)",
        industries: ["Port Services", "Technology", "Manufacturing", "Education"]
    },
    {
        slug: "honolulu",
        name: "Honolulu",
        state: "Hawaii",
        stateCode: "HI",
        population: "345,000",
        knownFor: "tourism, military, and transport",
        businessScene: "Pacific trade and hospitality center",
        techHub: false,
        region: "West",
        localKeyword: "Honolulu hospitality IT",
        uniqueFact: "Honolulu is the southernmost major US city.",
        nearbyCity: "Anchorage",
        nearbyCitySlug: "anchorage",
        timezone: "Hawaii-Aleutian Time (HST)",
        industries: ["Tourism", "Military", "Transportation", "Trade"]
    }
];
